VERSION 0.6
FROM eclipse-temurin:11-alpine
RUN apk add --update --no-cache gradle=7.2-r0
WORKDIR /gradle-project

deps:
    COPY build.gradle ./
    RUN gradle build
    SAVE IMAGE --ci --push ghcr.io/ricardf/earthly-playground:deps

build:
    FROM +deps
    COPY src src
    RUN gradle build
    RUN gradle install
    SAVE ARTIFACT build AS LOCAL build
    SAVE IMAGE --ci --push ghcr.io/ricardf/earthly-playground:build

docker:
    COPY +build/build/install/gradle-project/bin bin
    COPY +build/build/install/gradle-project/lib lib
    ENTRYPOINT ["/gradle-project/bin/java-example"]
    SAVE IMAGE --push ghcr.io/ricardf/earthly-playground
